name: Network Diagnostics Workflow

on:
  push:
    branches:
      - main

jobs:
  network-diagnostics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Network Diagnostic Commands
        run: |
          echo "Display current network interfaces and IP addresses"
          ip a

          echo "Display IP routing table"
          ip route

          echo "Show default gateway"
          ip route | grep default

          echo "Show DNS configuration"
          cat /etc/resolv.conf

          echo "Show network interface statistics"
          ifconfig -a || ip -s link

          echo "Ping a host to check connectivity"
          ping -c 4 google.com || echo "Ping failed"

          echo "Check TCP/UDP listening ports and open connections"
          ss -tuln

          echo "Show active connections"
          ss -s

          echo "Display all network sockets"
          netstat -tulnp || ss -tulnp

          echo "Trace the route to a host"
          sudo apt-get update && sudo apt-get install -y traceroute
          traceroute google.com || echo "Traceroute failed"

          echo "Perform DNS lookup for a domain"
          nslookup google.com || echo "nslookup command not found"

          echo "Alternative DNS query using dig"
          sudo apt-get install -y dnsutils
          dig google.com || echo "dig command failed"

          echo "Check the hostname of the system"
          hostname

          echo "Set hostname (temporary until reboot)"
          sudo hostname github-hostname

          echo "Download a file using curl"
          curl -O https://example.com/sample.txt || echo "curl failed"

          echo "Check network connectivity with wget"
          sudo apt-get install -y wget
          wget https://example.com || echo "wget failed"

          echo "Test internet connection via curl"
          curl -Is https://google.com | head -n 1 || echo "curl test failed"

          echo "Show firewall rules (ufw)"
          sudo ufw status || echo "ufw not active or installed"

          echo "Enable firewall (ufw)"
          sudo ufw enable || echo "Could not enable ufw"

          echo "Allow HTTP and HTTPS ports"
          sudo ufw allow 80 || echo "Failed to allow port 80"
          sudo ufw allow 443 || echo "Failed to allow port 443"

          echo "Deny incoming ping requests (ICMP)"
          sudo iptables -A INPUT -p icmp --icmp-type echo-request -j DROP || echo "iptables command failed"

          echo "List current iptables rules"
          sudo iptables -L -n -v || echo "iptables command failed"
