name: Linux Sysadmin Command Runner

on:
  push:
    paths:
      - '**/*.txt'
  workflow_dispatch:

jobs:
  run-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run All Sysadmin Command Files
        run: |
          echo "🚀 Starting Sysadmin Command Execution..."
          find . -type f -name "*.txt" | while read -r file; do
            echo "📄 Executing commands from: $file"
            grep -Ev '^\s*$|^\s*#' "$file" | while read -r cmd; do
              echo "▶️ $cmd"
              bash -c "$cmd"
              status=$?
              if [ $status -ne 0 ]; then
                echo "❌ Command failed with exit code $status"
              fi
            done
            echo "✅ Completed: $file"
            echo "----------------------------"
          done
