name: System Resource Check Workflow

on:
  push:
    branches:
      - main

jobs:
  system-resource-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run System Resource Analysis Commands
        run: |
          echo "Show total and free memory in human-readable format"
          free -h

          echo "Show memory usage by processes"
          ps aux --sort=-%mem | head -n 10

          echo "Show top memory-consuming processes dynamically"
          top -o %MEM -b -n 1 | head -n 20

          echo "Display swap usage"
          swapon --show

          echo "Display disk usage for all mounted file systems"
          df -h

          echo "Display disk usage per directory in current path"
          du -sh *

          echo "Display disk usage for all files and directories (recursive)"
          du -ah . | sort -rh | head -n 10

          echo "Show inode usage (file/directory count usage)"
          df -i

          echo "Show mounted file systems and types"
          mount | column -t

          echo "Display disk partitions and sizes"
          lsblk

          echo "Show detailed block device information"
          sudo fdisk -l || echo "fdisk not accessible"

          echo "Display disk I/O stats"
          iostat || echo "iostat command not found"

          echo "Display memory statistics"
          vmstat 1 5 || echo "vmstat command not found"

          echo "Check disk space usage with summary"
          sudo du -sh /home/* || echo "/home/* may not exist in runner"

          echo "Display partition usage in tree format"
          sudo apt-get update && sudo apt-get install -y tree
          sudo tree -L 2 / | head -n 50 || echo "tree command failed"

          echo "Check available and used RAM with details"
          cat /proc/meminfo | head -n 10

          echo "Show memory usage per user"
          ps -eo user,pmem | sort -k2 -nr | head

          echo "Check space occupied by each user in home directory"
          sudo du -sh /home/* || echo "/home/* not found"

          echo "List top 10 directories consuming space"
          sudo du -a / | sort -n -r | head -n 10

          echo "Display information about disk cache"
          sudo dmidecode -t memory || echo "dmidecode not accessible"

          echo "Check RAM slots and installed memory"
          sudo lshw -short -C memory || echo "lshw not accessible"

          echo "Check filesystem disk space usage (human-readable)"
          sudo df -Th

          echo "List mounted file systems in use"
          findmnt

          echo "Display all UUIDs of partitions"
          blkid || echo "blkid command not found"
