name: Run Shell Commands

on:
  push:
    branches:
      - main

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install required packages (for cal)
        run: |
          sudo apt-get update
          sudo apt-get install -y bsdmainutils

      - name: Execute Shell Commands
        run: |
          echo "Show current user"
          whoami

          echo "Show current directory"
          pwd

          echo "List files in the current directory"
          ls -l

          echo "Create a new directory"
          mkdir test_directory

          echo "Navigate into the new directory"
          cd test_directory

          echo "Create a new file"
          touch testfile.txt

          echo "Write some text into the file"
          echo 'This is a test file created in GitHub Actions' > testfile.txt

          echo "Display file content"
          cat testfile.txt

          echo "Append more content to the file"
          echo 'Another line added.' >> testfile.txt

          echo "Show file content again"
          cat testfile.txt

          echo "Rename the file"
          mv testfile.txt renamed_file.txt

          echo "Copy the file"
          cp renamed_file.txt copy_of_file.txt

          echo "List all files again"
          ls -l

          echo "Display disk usage of current directory"
          du -sh .

          echo "Display free disk space"
          df -h

          echo "Display current date and time"
          date

          echo "Display calendar"
          cal

          echo "Show system uptime"
          uptime

          echo "Show hostname"
          hostname

          echo "Show kernel version"
          uname -r

          echo "Show system information"
          uname -a

          echo "Display currently running processes"
          ps aux | head -10

          echo "Sleep command for 2 seconds (simulate a wait)"
          sleep 2

          echo "Remove copied file"
          rm copy_of_file.txt

          echo "Go one level back"
          cd ..

          echo "Remove the directory created"
          rm -r test_directory
